#!/bin/bash

# Unified build script for the entire application
# Builds field-validator, translator WebAssembly modules, frontend, and backend

set -e  # Exit on error

# Parse arguments
SKIP_DOCS=false
for arg in "$@"; do
    case $arg in
        --skip-docs)
            SKIP_DOCS=true
            shift
            ;;
    esac
done

echo "Starting unified build process..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check prerequisites
print_status "Checking prerequisites..."

# Check Rust
if ! command -v cargo &> /dev/null; then
    print_error "Rust/Cargo not found. Please install Rust."
    exit 1
fi
print_success "Rust found: $(cargo --version)"

# Check wasm-pack
if ! command -v wasm-pack &> /dev/null; then
    print_error "wasm-pack not found. Please install it with: cargo install wasm-pack"
    exit 1
fi
print_success "wasm-pack found: $(wasm-pack --version)"

# Check deno
if ! command -v deno &> /dev/null; then
    print_error "Deno not found. Please install Deno."
    exit 1
fi
print_success "Deno found: $(deno --version | head -1)"

# Function to build and bind a WASM crate using wasm-pack
build_wasm_crate() {
    local crate_dir=$1
    local out_name=$2
    local features=$3

    print_status "Building $out_name with wasm-pack..."

    local extra_args=""
    if [ -n "$features" ]; then
        extra_args="-- --features $features"
    fi

    wasm-pack build "$crate_dir" --target web --out-dir "../frontend/src/wasm" --out-name "$out_name" --release $extra_args --quiet

    # Remove unnecessary files generated by wasm-pack that weren't in the original build process
    rm -f "frontend/src/wasm/package.json" "frontend/src/wasm/.gitignore" "frontend/src/wasm/README.md"
}

# Build libraries
print_status "Building libraries..."

# Build field-validator
build_wasm_crate "field-validator" "field-validator" "wasm"

# Build translator
build_wasm_crate "translator" "translator" "wasm"

print_success "Libraries built and bindings generated"

# Build backend
print_status "Building backend server..."
cargo build --release -p appsec-server --quiet
if [ $? -eq 0 ]; then
    print_success "Backend build completed"
else
    print_error "Backend build failed"
    exit 1
fi

# Fetch fresh OpenAPI spec from backend
print_status "Fetching OpenAPI spec from backend..."
./target/release/appsec-server --dev > /tmp/backend.log 2>&1 &
BACKEND_PID=$!
disown $BACKEND_PID 2>/dev/null || true

sleep 3

if curl -s --max-time 5 http://localhost:4000/api/openapi.json > /tmp/openapi.json 2>/dev/null && [ -s /tmp/openapi.json ]; then
    mv /tmp/openapi.json frontend/src/generated/openapi.json
    print_success "OpenAPI spec fetched successfully"
else
    print_warning "Could not fetch OpenAPI spec from backend. Using existing spec if available."
fi

# Kill the backend process
kill $BACKEND_PID 2>/dev/null || true
sleep 1
kill -9 $BACKEND_PID 2>/dev/null || true

# Generate OpenAPI TypeScript client
print_status "Generating OpenAPI TypeScript client..."
cd frontend
deno install
export PATH="$PWD/node_modules/.bin:$PATH"
if [ -f "src/generated/openapi.json" ]; then
    deno run -A npm:@hey-api/openapi-ts --input src/generated/openapi.json --output src/generated/api-client --client @hey-api/client-fetch
    print_success "TypeScript API client generated"
else
    print_error "OpenAPI spec not found. Cannot generate TypeScript client."
    exit 1
fi
cd ..

# Build frontend
print_status "Building frontend..."
cd frontend
deno run build
if [ $? -eq 0 ]; then
    print_success "Frontend build completed"
else
    print_error "Frontend build failed"
    exit 1
fi
cd ..

# Build the documentation (optional - skipped if LaTeX not available or --skip-docs flag)
if [ "$SKIP_DOCS" = true ]; then
    print_warning "Documentation build skipped (--skip-docs flag)"
else
    cd documentation/latex
    DOC_OUTPUT=$(./generate.sh 2>&1)
    DOC_EXIT=$?
    cd ../..

    if [ $DOC_EXIT -eq 0 ]; then
        if echo "$DOC_OUTPUT" | grep -q "skipping documentation build"; then
            print_warning "Documentation build skipped (LaTeX not available)"
        else
            print_success "Documentation build completed"
        fi
    else
        print_error "Documentation build failed"
        exit 1
    fi
fi

print_success "All builds completed successfully!"
echo ""
echo "To run the application:"
echo "  cd backend && cargo run --release"
echo ""
echo "The backend will serve the frontend from the dist directory automatically."
