#!/bin/bash

# Unified build script for the entire application
# Builds password validator, WebAssembly, protobuf types, frontend, and backend

set -e  # Exit on error

echo "Starting unified build process..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check prerequisites
print_status "Checking prerequisites..."

# Check Rust
if ! command -v cargo &> /dev/null; then
    print_error "Rust/Cargo not found. Please install Rust."
    exit 1
fi
print_success "Rust found: $(cargo --version)"

# Check wasm-pack
if ! command -v wasm-pack &> /dev/null; then
    print_error "wasm-pack not found. Please install it with: cargo install wasm-pack"
    exit 1
fi
print_success "wasm-pack found: $(wasm-pack --version)"

# Check deno
if ! command -v deno &> /dev/null; then
    print_error "Deno not found. Please install Deno."
    exit 1
fi
print_success "Deno found: $(deno --version | head -1)"

# Check protoc
if ! command -v protoc &> /dev/null; then
    print_error "protoc not found. Please install protobuf compiler."
    exit 1
fi
print_success "protoc found"

# Function to build and bind a WASM crate using wasm-pack
build_wasm_crate() {
    local crate_dir=$1
    local out_name=$2
    local features=$3

    print_status "Building $out_name with wasm-pack..."

    local extra_args=""
    if [ -n "$features" ]; then
        extra_args="-- --features $features"
    fi

    wasm-pack build "$crate_dir" --target web --out-dir "../frontend/src/wasm" --out-name "$out_name" --release $extra_args --quiet

    # Remove unnecessary files generated by wasm-pack that weren't in the original build process
    rm -f "frontend/src/wasm/package.json" "frontend/src/wasm/.gitignore" "frontend/src/wasm/README.md"
}

# Build libraries
print_status "Building libraries..."

# Build field-validator
build_wasm_crate "field-validator" "field-validator" "wasm"

# Build translator
build_wasm_crate "translator" "translator" "wasm"

print_success "Libraries built and bindings generated"

# Generate protobuf types for frontend
print_status "Generating protobuf types for frontend..."
cd frontend
if [ -f "node_modules/.bin/protoc-gen-ts_proto" ]; then
    mkdir -p src/generated
    protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/generated --proto_path=../proto api.proto
    if [ $? -eq 0 ]; then
        print_success "Frontend protobuf types generated"
    else
        print_warning "Frontend protobuf generation failed (may not be critical)"
    fi
else
    print_warning "protoc-gen-ts_proto not found, skipping frontend protobuf generation"
fi
cd ..

# Build backend
print_status "Building backend server..."
cd backend
cargo build --release --quiet
if [ $? -eq 0 ]; then
    print_success "Backend build completed"
else
    print_error "Backend build failed"
    exit 1
fi
cd ..

# Build frontend
print_status "Building frontend..."
cd frontend
deno run build
if [ $? -eq 0 ]; then
    print_success "Frontend build completed"
else
    print_error "Frontend build failed"
    exit 1
fi
cd ..

print_success "All builds completed successfully!"
echo ""
echo "To run the application:"
echo "  cd backend && cargo run --release"
echo ""
echo "The backend will serve the frontend from the dist directory automatically."
