/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthFormLayout: typeof import('./components/auth/AuthFormLayout.vue')['default']
    AuthSubmitButton: typeof import('./components/auth/AuthSubmitButton.vue')['default']
    ConfirmPasswordField: typeof import('./components/auth/ConfirmPasswordField.vue')['default']
    EmailField: typeof import('./components/auth/EmailField.vue')['default']
    ForgotPasswordLink: typeof import('./components/auth/ForgotPasswordLink.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PasswordField: typeof import('./components/auth/PasswordField.vue')['default']
    RememberMeCheckbox: typeof import('./components/auth/RememberMeCheckbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusMessage: typeof import('./components/auth/StatusMessage.vue')['default']
    UsernameField: typeof import('./components/auth/UsernameField.vue')['default']
  }
}
